ucsb-cs56-w20/ucsb-courses-search

README.md

In this PR, we add an explanation in the README.md of how to set up the API key.

pc - add explantion to README.md

---

src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/Section.java
src/main/resources/templates/searchResults.html

This is a small PR fixing the check for when an entry in the list of meeting times for a course is a section or not. 
the previous check, s.secondaryStatus where s is a meeting time for a course, was not guaranteed to work. The new check depends on the value of a section for that meeting time (ends with 00 iff a lecture), and is more consistent.

goal - fixed thymeleaf code for determining if an entry is a section

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/CoursePageToCSV.java

Fixes #16. This PR makes opencsv quote csv values, ensuring commas will not break the structure of the csv.

Properly encode commas in CSV exports

---

CourseSearch/src/module-info.java
src/main/resources/templates/searchResults.html

* In this PR, we comment out the JSON results showing up on the Front Page.
This commented out code should probably be removed in a future update of the code, but we'll leave it for now since it is useful for debugging and for demonstrating how the code works during on boarding.
It might actually be good to instead have a feature toggle that allows the JSON to be shown (perhaps by a setting in the application.properties or the localhost.json)

Fix json results

---

heroku.json.SAMPLE
localhost.json.SAMPLE

This PR adds placeholders to the sample json for heroku and localhost where the
values of the GitHub OAuth client id and secret should be entered.

pc/xq - add GitHub OAuth config to sample json

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/Application.java
src/main/resources/templates/searchResults.html

This PR adds a feature that "Add" and "Drop" buttons show up by sections only if the user is authenticated. 
Changes:
* Add and drop buttons will not show up if the user is not logged in
* *searchResults* page is whitelisted for when you are not authenticated: you are still able to see a list of courses without having to log in.

ag - buttons show up if logged in

---

src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/Course.java
src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/TestCourse.java

In this PR, we add some methods to the `Course` object, along with test coverage of these methods.  This allow us to more easily list the "main instructor" in summary listing of courses.

pc - add method to get instructor from first section on list

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/CurriculumService.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/UCSBAcademicCurriculumService.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/controllers/SearchByCourseController.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/searches/SearchByCourse.java
src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/Quarter.java
src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/Course.java
src/main/resources/templates/fragments/bootstrap_nav_header.html
src/main/resources/templates/search/bycourse/fragments/form.html
src/main/resources/templates/search/bycourse/fragments/list.html
src/main/resources/templates/search/bycourse/results.html
src/main/resources/templates/search/bycourse/search.html
src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/TestQuarter.java
src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/TestCourse.java

In this PR, we add an MVP for a search by course feature.
The third menu now has an option where a user can enter a course to search for, a starting and ending quarter.  Basic information about the courses offered in those quarters is provided.
Future enhancements may include:
* adding information about the enrollments, as well as day/time/room, etc. 
* a list of TAs, and number of sections offered
* ability to download as a CSV
For most use cases of this page it is good to preserve the one line per lecture section structure though.

Pc search by course

---

src/main/resources/templates/search/bycourse/fragments/list.html

In this PR, we add quarter in both YYYYQ and QYY formats to the course search results.

pc - add quarter in both formats to course search

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/Application.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/UCSBAcademicCurriculumService.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/controllers/SearchByDeptController.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/results/CourseOffering.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/searches/SearchByDept.java
src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/CoursePage.java
src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/Section.java
src/main/resources/templates/fragments/bootstrap_nav_header.html
src/main/resources/templates/search/bycourse/fragments/title.html
src/main/resources/templates/search/bycourse/results.html
src/main/resources/templates/search/bydept/fragments/form.html
src/main/resources/templates/search/bydept/fragments/list.html
src/main/resources/templates/search/bydept/fragments/title.html
src/main/resources/templates/search/bydept/results.html
src/main/resources/templates/search/bydept/search.html

In this PR, we:
* Make it possible to search all levels "A" (grad and undergrad) by adding that feature to the
search service (to make this work in the API, you just don't pass anything for that parameter)
* Unprotect (don't require login) for all endpoints that start with `search/` (will eventually 
refactor so that all searches that don't update state are under that URL pattern)
* Add a search by department that will eventually replace the basic search, and has 
an improved format for results returned.

Pc search by dept

---

src/main/resources/templates/fragments/bootstrap_nav_header.html

In this PR, we reorganize the nav bar so that basic searches (that don't require login) are all together on the left, and the feature requiring login is at the right.

pc - reorganize nav bar

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controllers/SearchByDeptController.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/results/CourseListingRow.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/results/CourseOffering.java
src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/Section.java
src/main/resources/templates/fragments/bootstrap_nav_header.html
src/main/resources/templates/search/bydept/fragments/list.html

In this PR, we update the "by department search" to have listings that provide a more compact and readable version of the results.
We add enrollment, capacity, section number, enrollment code, indentation for secondaries, and lines to group primary and secondaries together.  
There is also code in place to show multiple timeLocations, but it is as yet untested.

Pc update by dept search

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controllers/SearchByCourseController.java
src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/Quarter.java
src/main/resources/templates/search/bycourse/fragments/form.html
src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/TestQuarter.java

In this PR, we add a programatic way to generate lists of quarters in forward or reverse chronological order, to use in populating drop down lists.
This PR only puts this into the byCourse search.  Adding it to the other searches can be done later.

pc - add more quarters to by course search

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controllers/CSDeptController.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/results/CourseListingRow.java
src/main/resources/application.properties
src/main/resources/templates/csdept/classroom/fragments/form.html
src/main/resources/templates/csdept/classroom/fragments/list.html
src/main/resources/templates/csdept/classroom/fragments/title.html
src/main/resources/templates/csdept/classroom/results.html
src/main/resources/templates/csdept/classroom/search.html
src/main/resources/templates/fragments/bootstrap_nav_header.html
src/test/java/edu/ucsb/cs56/ucsb_courses_search/csdept/CSDeptTest.java

In this PR, we add a new menu for CS-department specific functions, and a menu option to list all course meetings that take place in department-controlled classrooms. 
Currently, the list is hard-coded. Future work should move this to an `application.properties` value and print the list of department-controlled classrooms in the header of the page.

AL/PC - CS Department Controlled Classroom Search

---

.github/workflows/maven.yml

In this PR, we set up GitHub Actions as the CI system for this project.
Moving forward, we'll remove Travis-CI

pc - add github actions for ucsb-courses-search

---

.travis.yml

This commit removes .travis.yml because we are no longer going to use Travis-CI as our CI system;
we've switching to GitHub actions

pc - remove .travis.yml

---

src/main/resources/templates/searchResults.html

In this PR, we mark the old  search results view as deprecated.
Programmers should add features to the new byDept view and the search on the home page should go away.

pc - mark searchResults.html as deprecated

---

README.md
heroku.json.SAMPLE
localhost.json.SAMPLE
pom.xml
src/main/java/edu/ucsb/cs56/ucsb_courses_search/entity/ArchivedCourse.java
src/main/java/edu/ucsb/cs56/ucsb_courses_search/repository/ArchivedCourseRepository.java
src/main/resources/application.properties

This PR adds support for accessing the courses API archive we hosted on MongoDB Atlas. An `app.mongodb.username` and `app.mongodb.password` are now required in order to connect to this database.

Add support for accessing private MongoDB API mirror 

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/service/UCSBBuildingService.java

In this PR we fix a bug that affects the new links to buildings introduced by an earlier PR.
The links worked on localhost, but not Heroku.
The reason is explained in [this Stack Overflow answer](https://stackoverflow.com/a/35727761)

Fix building link bug

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/CSDeptController.java
src/main/resources/templates/fragments/generic_result_table.html

Since on the Cs dept page the courses are sorted by the building location and not by course name, all the respective courses and sections have black lines between them to make it uniform. This change was made only for the Cs dept search results page. The issue this fixes is https://github.com/ucsb-cs56-w20/ucsb-courses-search/issues/136

Sh -cs dept sorting

---

src/main/java/edu/ucsb/cs56/ucsb_courses_search/service/UCSBAcademicCurriculumService.java

This morning, I discovered that the GitHub Actions jobs were logging our UCSB API keys, and those logs are view-able by anyone with a GitHub account, regardless of their affiliation with this organization. 
(It's essentially public information now).
This change removes such logger statements so they can no longer appear in GitHub Actions logs and become public information. You can verify this by searching the logs on this commit for `apikey`. The only two results you should find are the ones that mention this branch name.

AL - Remove API key logger statements
