.gitignore, src/main/resources/templates/fragments/basic_search_form.html, src/test/java/edu/ucsb/cs56/ucsb_courses_search/HomePageTest.java
In this pull request we add the submit button for the form
=> Yr add search button

Procfile
In this pull request, we add a Procfile so that Heroku knows how to run our app
=> pc - add Procfile for Heroku

.gitignore, src/main/resources/templates/fragments/bootstrap_nav_header.html
Fixed the Nav Bar to include Teams
=> Fixed NavBar stuff

src/main/resources/templates/searchResults.html
In this PR, we add section times to the display of course results returned.
=> pc - add section times

.gitignore, pom.xml, src/main/java/edu/ucsb/cs56/ucsb_courses_search/CSVDownloadController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/CoursePageToCSV.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/SearchController.java, src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/Section.java, src/main/resources/templates/fragments/basic_search_form.html
In this PR, we add a capability to download a CSV file of courses.
=> Pc download csv

src/main/resources/templates/fragments/bootstrap_nav_header.html
* In this PR, we change the Navbar brand to UCSB Courses Search.
* This is a cleaned up version of PR #20  by @vpasupathyucsb  which might end up being moot (and closed)
=> Fix ui changes

pom.xml, src/main/java/edu/ucsb/cs56/ucsb_courses_search/controllers/CourseController.java, src/main/resources/templates/courseschedule/index.html, src/test/java/edu/ucsb/cs56/ucsb_courses_search/BootstrapTestHelper.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/HomePageTest.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/NavigationTestHelper.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/OAuthUtils.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/courseschedule/CourseScheduleTest.java
In this PR, we:
* Fix a bug where the drop downs didn't work on the `"See My Schedule" page (`/courseschedule`)
because the scripts were not being loaded.
* Add test coverage to the "See My Schedule" page (`/courseschedule`) to ensure that
* the  page loads when the user is logged in
* the page has the correct title
* the nav bar and footer are loaded
* the CSS and Javascript files are loaded.
Also note that this PR has an example of creating a Mock for a database table (spring boot "repository" pattern).
=> pc - fix dropdowns and add tests for CourseController

src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/Quarter.java, src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/TestQuarter.java
In this PR, we add a utility method for dealing with UCSB quarters, plus test coverage.
=> pc - add utility method for quarters

src/main/java/edu/ucsb/cs56/ucsb_courses_search/downloaders/CoursePageToCSV.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/entities/Course.java, src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/Quarter.java, src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/Course.java, src/main/resources/templates/courseschedule/index.html, src/main/resources/templates/fragments/bootstrap_nav_header.html, src/main/resources/templates/searchResults.html, src/test/java/edu/ucsb/cs56/ucsb_courses_search/courseschedule/CourseScheduleTest.java, src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/TestQuarter.java, src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/TestCourse.java
In this PR we:
* Add additional methods and unit test to the Quarter method for converting between QXX and YYYYQ formats
* Clarify and cleanup the global navigation
* Simply the mocking of the CourseRepository in the testing of the CourseController
* Get rid of Lombok in the Course object for converting from the API JSON, and add proper getters and setters (using a generator provided by VS Code.)
=> pc - add quarter to personal schedule

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controllers/SearchByCourseController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/results/CourseOffering.java, src/main/resources/templates/search/bycourse/fragments/list.html
In this PR, we update the results returned by the "by course" search to be easier to read and provide more information, including course capacity and enrollment.
=> pc - update by course search

src/main/resources/templates/csdept/classroom/fragments/form.html, src/main/resources/templates/fragments/basic_search_form.html, src/main/resources/templates/fragments/instructor_search_form.html, src/main/resources/templates/search/byinstructor/fragments/form.html, src/main/resources/templates/search/byinstructor/specific/fragments/form.html
Note that we really ought to factor this out into a method that produces this HTML
and can take the start and end quarter from the properties file
=> pc - add Spring 2020 to menus

src/main/resources/templates/fragments/generic_result_table.html, src/main/resources/templates/searchResults.html
Our friend Jack ( me ), accidentally deleted the front-end button for adding courses to the schedule while refactoring all the search result pages. 
The button is back and now shows up on the front page, the by department search, as well as the search by instructor search.
=> jk - added course schedule add button to generic_result_table

src/main/resources/templates/fragments/generic_result_table.html
In this PR, we address a problem where the byDept search was only running into a render error with the Add button for the personal schedule.
=> pc/rx - fix html in generic_result_table.html

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/SearchController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/model/UCSBBuilding.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/service/UCSBBuildingService.java, src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/TimeLocation.java, src/main/resources/templates/fragments/generic_result_table.html, src/main/resources/templates/searchResults.html, src/main/resources/ucsb_buildings.json
Finished this story- ep/sm/cm 
made building codes in search results into links to openrouteservice map centered on UCSB campus with a pin at location.
=> W 7pm d basic maps

src/main/java/edu/ucsb/cs56/ucsb_courses_search/repository/ArchivedCourseRepository.java
Provides a good starting point for the search by instructor team to get a hold of MongoDB queries.
=> add example mongodb query for searching by instructor name

src/main/resources/templates/csdept/classroom/fragments/list.html
removes the duplicate 'courses' title from the results page
=> sh - removed the duplicate courses title from the cs dept search results

src/main/resources/templates/fragments/course_details_modal.html, src/main/resources/templates/fragments/generic_result_table.html
Adding a modal as a separate fragment to avoid nested tables as well as clean up code.
=> Adding modal as a separate fragment

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/CSVDownloadController.java
fixed bug - file would not download as a csv file
*tested on chrome browser
- originally: file would download without any extension
- now: downloads as a .csv and shows data in a spreadsheet (excel)
*needs to verify if it works for other browsers besides chrome
=> tl - fixed .csv download bug

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/CourseController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/entity/Course.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/model/result/CourseListingRow.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/repository/CourseRepository.java, src/main/resources/templates/fragments/generic_result_table.html
Before this pull request, when click ADD for a section, it only added the section, not the associated lecture.
Now, it adds the associated lecture as well.
=> jp/pc - implemented automatic adding of associated lecture

README.md, heroku.json.SAMPLE, localhost.json.SAMPLE, src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/advice/FeatureToggleControllerAdvice.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/service/FeatureToggleService.java, src/main/resources/application.properties, src/main/resources/templates/fragments/bootstrap_nav_header.html, src/test/java/edu/ucsb/cs56/ucsb_courses_search/BootstrapTestHelper.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/HomePageTest.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/courseschedule/CourseScheduleTest.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/csdept/CSDeptTest.java
In this PR, we add a FeatureToggleService that can be autowired into any Java class in the application.
Feature Toggles are generally used to selectively enable features in an app while they are being incrementally developed.  The usual practice is to have the toggle "false" (or "off") in production, and "true" (or "on") in development.  That allows you to put feature into your app that are perhaps still only "half way done", and incrementally introduce them into the code base.    
To use this service:
* Add your new feature flag into `application.properties` with a value of false.  The naming convention is `app.feature.your_feature_name_here`
* Add an instance variable for your new feature flag into `src/main/java/edu/ucsb/cs56/ucsb_courses_search/service/FeatureToggleService.java` and …
=> (Staff) Multiple schedule feature toggle

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/CourseController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/entity/ScheduleItem.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/repository/ScheduleItemRepository.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/courseschedule/CourseScheduleTest.java, src/test/java/edu/ucsb/cs56/ucsb_courses_search/csdept/CSDeptTest.java
In this PR, we renamed Course to ScheduleItem because it might conflict with the new course definition from MongoDB.
=> ch/al/jj/jz/ks - renamed course to ScheduleItem

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/CourseController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/ScheduleController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/entity/Schedule.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/entity/ScheduleItem.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/repository/ScheduleItemRepository.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/repository/ScheduleRepository.java, src/main/resources/data.sql, src/main/resources/templates/courseschedule/index.html, src/main/resources/templates/fragments/bootstrap_nav_header.html, src/main/resources/templates/schedule/index.html
created the base implementation for a way to store multiple schedules
added a drop down to view schedule names
=> T 6pm b base schedule

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/SearchByCourseController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/SearchByDeptController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/SearchByGEController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/SearchByInstructorController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/SearchController.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/service/CurriculumService.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/service/FinalExamService.java, src/main/java/edu/ucsb/cs56/ucsb_courses_search/service/UCSBAcademicCurriculumService.java, src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/Course.java, src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/FinalExam.java, src/main/resources/templates/fragments/course_details_modal.html
Also added FinalExamService used to receieve Final Exam JSON data
=> kg - Added Final Exam info

src/main/java/edu/ucsb/cs56/ucsb_courses_search/controller/CourseController.java, src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/v1/classes/FinalPage.java
Fixed bug where a lab final wouldn't show up, and trying to see the finals after adding a lab section would cause an error.
=> rh - fixed bug where adding a lab section caused error

README.md
In this PR, we add some comments to the README.  This is a demo for Chris to show the entire workflow.
=> pc/ch - add brownfield note to README.md
